apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx
            port:
              number: 8090
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx
  labels:
    app: nginx
spec: 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector: 
    app: nginx
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
         app: nginx
    spec: 
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 8090
          name: http
        volumeMounts:
        - name: www-data
          mountPath: /var/www/index.html
          subPath: index.html
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
        - name: www-data
          configMap:
            name: nginx-conf
            items:
              - key: index.html
                path: index.html
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf        
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8090;
          server_name  localhost;
          location / {
            root   /var/www/;
            index  index.html;
        }
      }
    }
  index.html: |
    Hello SCRIBETECH